```{=latex}
\selectlanguage{estonian}

```

# Individual experiences with chlorine dioxide (CDS)

Regarding the topic of my individual presentation i had a dilemma: do i want to tell you something about math or on medicine? i have a lot of experience with math and not so much in medicine. This is why i chose the latter one.

The human body is an automated system in which a huge number of processes are carried out by a huge number of workers. According to the second law of thermodynamics, there is no process that ends without leaving waste. If a person lives a healthy life, his body can take care of cleaning body from waste products. To benefit from the luxurious tastes, smells, and touches of our reality by consuming more substances that are not meant for the human body to consume would create too much waste for the body to deal with. If the human body is not able to get rid of all waste products by itself, waste products start to accumulate in the body. you can imagine that this classroom is full of waste. Can we move our bodies with so much waste? can we do our job effectively in this situation? If there are too many waste products inside the body, it means getting sick. In such situations, the tendency is to call for help and order a cleaning service from the pharmaceutical industry. Most pharmaceutical products have negative side effects, which means that these so-called workers clean the room, transport the waste to another room and leave it there. Some other medications simply sweep the waste under the rug, so to speak. For example, *Ibuprofen* hides pain but does not remove its source. There are only a few pharmaceutical products that can do a professional, high-quality cleaning job. they say one such product is called *Aspirin*. Another such product is chlorine dioxide, which can distinguish between harmful and friendly cells in the human body and acts accordingly when in the human body. It burns all waste, kills all pathogens, and leaves the human body unharmed.

Some people find chlorine dioxide adorable and superior because of its capabilities. Some other people tend to censor every piece of information about chlorine dioxide. This controversy caused my high interest: who is right? i would like to say that the ones who are not right are left because they are left alone, untouched by chlorine dioxide. Knowledge can be acquired through experience.

So I bought the components to make Chloride Dioxide. i let them sit for 23 days without touching them because i had no reason to use them. Then on May 24, 2021, a running event took place at Peetri Kindergarten-Primary School, where I worked at the time, and I didn't want to miss it. The problem was that I had pain in one of my knees, so I could only run backward. It would have been so much more enjoyable to keep running and to achieve that ability I opened the bottles and mixed up my first dose of Chlorine Dioxide Solution (CDS). I applied it with dimethyl sulfoxide (DMSO) to my skin around that knee the night before the race and the morning of the same event. Just moments before I started the pain was gone and never came back. I just got the answer to my question, who was right? CDS worked, although I only had external experience with it so far.

As i knew about CDS and that it is a disinfectant and used as a means for purifying water i was curious whether there is a protocol for using CDS for cleaning teeth. i found the protocol and started to use CDS for cleaning my teeth.

On February 23, 2022, I began to feel the movement of suspicious forces in my throat. At the same time, there was a fire in my capital. This was the beginning of the violent attacks on my body by foreign military forces. Around 11 o'clock on February 24th, the attacks intensified and I felt a change in the temperature of the surface of my body caused by a fire inside my body. The temperature did not have a homogeneous trend, jumping around $310.65 \times K$ and $310.95 \times K$. Measured some peaks at $311.15 K$, but we can't find these temperature values in the official statistics, which were probably cyber-censored. Even Greta Thunberg's friends couldn't help me. While the rocket attacks had taken place mainly in the capital, fires could also be seen on the outskirts of the hips, which spread to the legs. Meanwhile, the center of the chest also shone slightly to the left. Friendly relief forces had tried to defuse the situation. After the arrival of the seventh regiment, they managed to force some of the pathogens to escape through the mouth. During the second exile, they caused injuries to the throat area, the consequences of which were still felt on February 25. Then I put a numerical limit on the incoming friendship regiments - only one pair instead of three. From time to time foreign soldiers came out coughing. The whole state was dizzy.

This is an unprecedented case in at least the last eight years when not a single foreign visit has been canceled due to an attack by foreign legions. The last time we felt hot weather was quite a while ago and then I got the temperature right for the day. In any case, in the state of war at that time, I did not consider a diplomatic visit to the mechanical laboratory possible and hoped that I would be able to carry out my duties when my physical world was once more at peace.

Regrettably, there was no piece of the state of my body in the news because the state in Ukraine was more important to them as had also been the vaccines the only antidotes instead of CDS. Probably it was *Covid-19 omicron* that attacked the realm of my body. Fasting with using CDS according to *Protocol 1000* made my body heal within four days and as we hear the fever in Ukraine still lasts as they would not accept using a metaphorical CDS for solving the issue.

*Protocol 1000* means three pairs of drops each hour eight hours a day 21 days long. i went on and even in a school building i created and consumed CDS in order to achieve a deep after-cleansing. i made a mistake by using birch juice instead of distilled water as i felt worse after each dose than before. So after seven and half days, i stopped. i thought had yet another answer to the question of who was right because now i know that CDS also works internally. i do not need more answers.

So who was right? The people who find CDS adorable and treat it as a universal antidote are right. And people who want to suppress the usage of CDS are also right as i can doubt them having fear. However, by the end of the day, they are not right but they are left over in suffering.

i can tell you so much more about CDS: its history, protocols, chemical reaction equations with calculations, and success stories of other people however the time limit for my presentation is not sufficient for anything more unless you raise some questions and we can start discussing right now.

To conclude i have a suggestion for you: If you are able to live a healthy life then you do not have to worry about the condition of your body becoming bad. However, if you do not want or are not able to live a healthy life then it is wise to have Master Mineral Solution (sodium chloride) and an acid close to you just in case.

i might not be able to answer all your questions. In such a case i write the question down and prepare an answer that will appear in my paper on the very same topic that i am currently in the process of writing. So feel free to shoot your questions and remarks!

```{=latex}
\selectlanguage{english}

```
